on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore .NET dependencies
      run: dotnet restore AAA
    - name: Build .NET project
      run: dotnet build AAA --no-restore
    - name: Run .NET tests
      run: dotnet test AAA --no-build --verbosity normal